on:
  # TODO: Uncomment this to run the workflow on a nightly basis.
  #schedule:
  #  - cron: '0 0 * * *'

  # Allow manually triggered workflows by maintainers without any parameters to
  # trigger a proactive rebuild (e.g. when a new package lands)
  workflow_dispatch: {}

name: Create Release

# Don't run multiple releases concurrently.
concurrency: release

jobs:
  release:
    name: Update workstation configuration
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    # !! TODO: REPLACE THIS WITH OUTPUT FROM INSTRUCTIONS IN setup/README.md !!
    - uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: projects/TODO/locations/global/workloadIdentityPools/TODO/providers/TODO
        service_account: TODO@TODO.iam.gserviceaccount.com
    # !! TODO: REPLACE THIS WITH OUTPUT FROM INSTRUCTIONS IN setup/README.md !!

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.3.*'
        terraform_wrapper: false

    - run: |
        terraform init
        terraform apply -auto-approve
